#pragma once

#define COSMAC_MOUSE_BUTTON_1         0
#define COSMAC_MOUSE_BUTTON_2         1
#define COSMAC_MOUSE_BUTTON_3         2
#define COSMAC_MOUSE_BUTTON_4         3
#define COSMAC_MOUSE_BUTTON_5         4
#define COSMAC_MOUSE_BUTTON_6         5
#define COSMAC_MOUSE_BUTTON_7         6
#define COSMAC_MOUSE_BUTTON_8         7
#define COSMAC_MOUSE_BUTTON_LAST      COSMAC_MOUSE_BUTTON_8
#define COSMAC_MOUSE_BUTTON_LEFT      COSMAC_MOUSE_BUTTON_1
#define COSMAC_MOUSE_BUTTON_RIGHT     COSMAC_MOUSE_BUTTON_2
#define COSMAC_MOUSE_BUTTON_MIDDLE    COSMAC_MOUSE_BUTTON_3